game:
  name: mountaincar_cont
  version: MountainCarContinuous-v0
  #render_mode: human
training:
  alg: TD3
  timesteps: 300000
  episodes: 5000
  save_model: true
  name_tag: "_del"
  #vectorized: true
  #num_envs: 4
model:
  continuous: true
  nn_type: DNN
  loss: MSE
  activation: relu
  layer_args:
    - layer_type: fcl
      n_out: 400
    - layer_type: fcl
      n_out: 300
parameters:
  lr_critic: 1.0e-3
  lr_actor: 1.0e-3
  #gamma: 0.995
  #buffer_size: 200000
  batch_size: 256
  learning_starts: 256
  train_freq: 1
  gradient_steps: 1
  noise_type: OU
  noise_std: 0.5
  #tau: 1
  seed: 5
