game:
  name: cartpole
  version: CartPole-v1
training:
  alg: DQN
  timesteps: 100000
  save_model: true
  name_tag: "_final"
  double_dqn: true
model:
  nn_type: DNN
  loss: Huber
  activation: relu
  layer_args:
    - layer_type: fcl
      n_out: 256 #32
    - layer_type: fcl
      n_out: 256 #32
parameters:
  lr: 0.0005
  seed: 10
  batch_size: 64
  buffer_size: 100000
  gamma: 0.99
  gradient_steps: 128
  learning_starts: 1000
  epsilon: 1
  epsilon_min: 0.04
  exp_frac: 0.16 #150 CHANGE EPISODE LOOP TO STEPS; CHange to eps fraction
  #epsilon_decay: 0
  target_update_interval: 10
  step_repeat: 1
  train_freq: 256
  tau: 1 # This is just hard update. remove update method param.
