game:
  name: mountaincar
  version: MountainCar-v0
  #frame_stack: 4
  #max_episode_steps: 100 #5000
training:
  alg: DQN
  double_dqn: true
  timesteps: 120000
  save_model: true
  name_tag: "_testnew"
model:
  nn_type: DNN
  loss: Huber
  activation: relu
  layer_args:
    - layer_type: fcl
      n_out: 256
    - layer_type: fcl
      n_out: 256
parameters:
  lr: 0.004
  #seed: 1000
  batch_size: 128
  buffer_size: 10000
  gamma: 0.98
  gradient_steps: 8
  learning_starts: 1000
  epsilon: 1
  epsilon_min: 0.07
  exp_frac: 0.2 #150 CHANGE EPISODE LOOP TO STEPS; CHange to eps fraction
  #epsilon_decay: 0
  target_update_interval: 600
  step_repeat: 1
  train_freq: 16
  tau: 1 # This is just hard update. remove update method param.

